version: "3"
services:
  influxdb:
    image: influxdb:1.5-alpine
    # volumes:
    # - ./data:/var/lib/influxdb
    ports:
    - "8083:8083"
    - "8086:8086"
    environment:
    - INFLUXDB_DB=healthdata
    - INFLUXDB_ADMIN_USER=admin
    - INFLUXDB_ADMIN_PASSWORD=changeme
    - INFLUXDB_READ_USER=user
    - INFLUXDB_READ_USER_PASSWORD=password

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
    - "3000:3000"
    links:
    - influxdb